version: '3.3'

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: seg123
      MYSQL_DATABASE: db

  app:
    links:
      - cache
      - db
    depends_on:
      - db
      - cache
    build:
      context: ./conf/wp
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./wordpress_data:/var/www/html
      - ./conf/wp/wp-config.php:/var/www/html/wp-config.php

  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/proxy/cert:/etc/nginx/ssl
    depends_on:
      - app 
    links:
      - app

  cache:
    image: redis
